<a href="https://colab.research.google.com/github/arsal-imran/DA-Workshop/blob/main/DA_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks_np = np.array([78, 85, 90, 66, 88])
marks_np

array([78, 85, 90, 66, 88])

In [ ]:
marks_np.mean()
print("Avg: ", marks_np.mean())
print("Max: ", marks_np.max())
print("Min: ", marks_np.min())

Avg:  81.4
Max:  90
Min:  66


In [ ]:
marks_np + 5

array([83, 90, 95, 71, 93])

In [ ]:
scores = np.array([
    [78, 85, 90],
    [88, 92, 95],
    [70, 75, 80]
])

scores

array([[78, 85, 90],
       [88, 92, 95],
       [70, 75, 80]])

In [ ]:
scores[0][0]

np.int64(78)

In [ ]:
scores [0][1]

np.int64(85)

In [ ]:
import pandas as pd

In [ ]:
prices = [10, 20, 30, 40, 50]

In [ ]:
my_series = pd.Series(prices)
my_series
print(my_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
items=["Apple","Mango","Banana","Cherry","Orange"]

In [ ]:
items
stock = pd.Series(prices, index = items)
print (stock)

Apple     10
Mango     20
Banana    30
Cherry    40
Orange    50
dtype: int64


In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Danish", "Murtuza"],
    "Age": [22, 24, 21, np.nan, 21],
    "CGPA": [3.6, 3.9, 3.2, 3.5, 3.7]
}


df = pd.DataFrame(data)
print(df)

      Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
2    Ahmed  21.0   3.2
3   Danish   NaN   3.5
4  Murtuza  21.0   3.7


In [ ]:
df.head()

Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
2    Ahmed  21.0   3.2
3   Danish   NaN   3.5
4  Murtuza  21.0   3.7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     4 non-null      float64
 2   CGPA    5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes


In [ ]:
df.describe()

Age      CGPA
count   4.000000  5.000000
mean   22.000000  3.580000
std     1.414214  0.258844
min    21.000000  3.200000
25%    21.000000  3.500000
50%    21.500000  3.600000
75%    22.500000  3.700000
max    24.000000  3.900000

In [ ]:
df["CGPA"]

0    3.6
1    3.9
2    3.2
3    3.5
4    3.7
Name: CGPA, dtype: float64

In [ ]:
df[["Name", "Age"]]

Name   Age
0      Ali  22.0
1     Sara  24.0
2    Ahmed  21.0
3   Danish   NaN
4  Murtuza  21.0

In [ ]:
df[df["CGPA"] > 3.5]

Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
4  Murtuza  21.0   3.7

In [ ]:
df.iloc[1]

Name    Sara
Age     24.0
CGPA     3.9
Name: 1, dtype: object

In [ ]:
df[df["Name"] == "Sara"]

Name   Age  CGPA
1  Sara  24.0   3.9

In [ ]:
df.isna().sum()

Name    0
Age     1
CGPA    0
dtype: int64

In [ ]:
df.dropna()

Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
2    Ahmed  21.0   3.2
4  Murtuza  21.0   3.7

In [ ]:
df

Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
2    Ahmed  21.0   3.2
3   Danish   NaN   3.5
4  Murtuza  21.0   3.7

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

Name   Age  CGPA
0      Ali  22.0   3.6
1     Sara  24.0   3.9
2    Ahmed  21.0   3.2
3   Danish  22.0   3.5
4  Murtuza  21.0   3.7